### ISSUE TITLE
exclude blocked ranges from push to dnsvs

### ISSUE THREAD

**Issue by alexanha** [particleKIT/hostlist#10]
Introduce a conifg, e.g. `dnsvs_exclude_range` which is not managed by this tool. Reason: some addresses may e.g. refer to externally managed switches.

**Comment by robinro** [comment]
This is currently done via the ipranges `external` and `internal`.

What about having a group `dnsvs` to which one can add/remove hosts?
This would fit nicer to the recent changes to use groups for everything (ansible, munin, known_hosts, ...).

**Comment by alexanha** [comment]
Hm, that means when adding, only existing computers in this group are synced, and upon removal only those which were in this group are removed? How to decide the latter?

**Comment by robinro** [comment]
Our sync is one-way anyhow: We generate a local list of hosts that should be synced and then on the remote remove all hosts that are not there locally and add all hosts that are missing.
We only need to adjust the list of hosts we generated locally to affect this behaviour.

**Comment by robinro** [comment]
This was fixed by importing the single entry that was affected in our list.
