### ISSUE TITLE
Use ansible-cmdb for the web output

### ISSUE THREAD

**Issue by robinro** [particleKIT/hostlist#11]
The web output could be replaced by https://github.com/fboender/ansible-cmdb

**Comment by martingabelmann** [comment]
This seems to be very promising.  
We might create an own template, based on the [default](https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/data/tpl/html_fancy.tpl) one, for things like user, institute, date_bought etc. (maybe create it dynamically based on the additional hostvars eg. if a hostvar is set on more than `n` hosts it becomes a column in the weboutput/template)
